# permissions for end users to edit certmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certmanager-editor-role
rules:
- apiGroups:
  - operator.cert-manager.io
  resources:
  - certmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.cert-manager.io
  resources:
  - certmanagers/status
  verbs:
  - get
